export const recruitmentUrl = "https://www.daangn.com/kr/group/%EB%B6%80%EC%82%B0-%EC%82%AC%EC%A7%81%EB%8F%99-%EB%B0%94%EC%9D%B4%EB%B8%8C%EC%BD%94%EB%94%A9-%EB%AA%A8%EC%9E%84-vxbz4quk5ntg/";

export const siteContent = {
  brand: "AutoSites",
  navigation: [
    { label: "1일 체험", href: "/experience" },
    { label: "준비작업", href: "/setup" },
    { label: "AutoSites 소개", href: "/about" },
    { label: "4주 교육과정", href: "/course" },
    { label: "무료 자료", href: "/resources" },
    { label: "신청 문의", href: recruitmentUrl },
  ],
  hero: {
    eyebrow: "BUSAN · BEGINNER 4-WEEK CLASS",
    title: "혼자서는 미뤘던 홈페이지,\n이번 4주에는 완성하세요.",
    description: "무엇부터 시작할지 몰라 멈췄어도 괜찮습니다. 같은 화면을 보며 하나씩 해결하고, 마지막에는 휴대폰으로 보여줄 수 있는 내 홈페이지 주소를 가져갑니다.",
    primaryAction: { label: "내가 따라갈 수 있는지 물어보기", href: recruitmentUrl },
    secondaryAction: { label: "4주 커리큘럼 보기", href: "/course#curriculum" },
    facts: ["2기 2026. 10. 10 시작", "매주 토요일 오후 6시–8시", "4주 전체 80,000원", "부산 · 최대 8명"],
    achievement: "1기 4주 과정 수료 완료 · 진행률 100%",
    note: "HTML · CSS · JavaScript를 몰라도 같은 화면을 보며 따라갈 수 있습니다.",
  },
  beginnerStory: {
    eyebrow: "YOUR 4-WEEK STORY",
    title: "막막했던 시작이\n내 홈페이지 주소가 되기까지",
    description: "이 수업은 이미 준비된 사람보다 혼자 검색하다 멈췄던 초보자를 위해 만들어졌습니다.",
    chapters: [
      { number: "01", label: "시작 전", title: "어디서부터 해야 할지 막막합니다.", description: "설치할 것은 많고 오류가 나오면 무엇을 검색해야 하는지도 몰라 아이디어를 계속 미뤄 둡니다." },
      { number: "02", label: "수업 중", title: "막힌 화면을 함께 보며 넘습니다.", description: "Codex에 요청하는 법부터 오류 확인, GitHub 저장과 Vercel 배포까지 같은 순서로 직접 따라갑니다." },
      { number: "03", label: "4주 뒤", title: "내가 만든 주소를 직접 보여줍니다.", description: "반응형 홈페이지, GitHub 저장소, 실제 운영 URL과 다시 수정하고 배포하는 방법이 남습니다." },
    ],
    result: "혼자서는 멈췄던 순간을 함께 넘고, 4주 뒤 실제 홈페이지 주소를 가져가세요.",
  },
  cohortProof: {
    eyebrow: "COHORT 01 · REAL RESULT",
    title: "먼저 시작한 1기도\n같은 자리에서 출발했습니다.",
    description: "1기는 4주 과정을 모두 수료했고, 직접 만든 서비스를 실제 주소로 운영하고 있습니다. 설명보다 결과를 먼저 확인해 보세요.",
    facts: ["4주 과정 수료", "진행률 100%", "실제 운영 작품 공개"],
    project: {
      label: "1기 수강생 작품 · 운영 중",
      title: "MOVIEBOX",
      description: "인기 영화, 현재 상영작, 개봉 예정작과 상세정보를 탐색할 수 있는 반응형 영화 정보 서비스입니다.",
      href: "https://bb-movie-rho.vercel.app/",
    },
  },
  sourceProjects: [
    { type: "ZIP", title: "MOVIEPIK 영화 사이트 소스", description: "영화·TV 탐색, 검색, 상세정보와 찜 기능이 포함된 Vite·React 예제입니다. TMDB 토큰은 제거되어 있으며 직접 발급한 키를 설정해야 합니다.", stack: "Vite · React · TMDB API", href: "/downloads/moviepik-source.zip", fileName: "moviepik-source.zip" },
    { type: "ZIP", title: "TRIP 여행 사이트 소스", description: "관광지·축제 검색, 여행지 상세정보, 찜과 일정 계획 기능이 포함된 Vite·React 예제입니다. 관광 API 키는 제거되어 있으며 직접 발급한 키를 설정해야 합니다.", stack: "Vite · React · Tour API", href: "/downloads/trip-source.zip", fileName: "trip-source.zip" },
  ],
  experience: {
    eyebrow: "ONE-DAY · 2-HOUR EXPERIENCE",
    title: "AI와 함께 2시간 만에\n내 홈페이지 공개하기",
    description: "코딩을 배우는 데서 끝나는 체험이 아닙니다. 만들고 싶은 홈페이지를 AI에게 설명하고, 직접 수정한 뒤 다른 사람에게 보여줄 수 있는 인터넷 주소까지 완성합니다.",
    audience: ["코딩이 처음인 분", "홈페이지 아이디어만 가지고 있던 분", "4주 과정 전에 수업 방식을 경험하고 싶은 분"],
    outcomes: ["내 문구가 들어간 1페이지 홈페이지", "휴대폰에서도 보기 좋은 화면", "다른 사람에게 공유할 수 있는 실제 URL"],
    schedule: [
      { time: "00:00–00:15", title: "만들 홈페이지 정하기", description: "소개할 내용과 방문자가 해야 할 행동 한 가지를 정합니다." },
      { time: "00:15–00:30", title: "AI에게 첫 제작 요청", description: "어려운 개발 용어 없이 원하는 화면을 문장으로 설명합니다." },
      { time: "00:30–01:00", title: "내 문구와 색상으로 수정", description: "제목, 소개, 버튼과 색상을 내 목적에 맞게 바꿉니다." },
      { time: "01:00–01:15", title: "모바일 화면 확인", description: "휴대폰에서도 읽고 누르기 편한지 직접 점검합니다." },
      { time: "01:15–01:45", title: "인터넷 주소로 공개", description: "GitHub와 Vercel을 연결해 실제 URL로 배포합니다." },
      { time: "01:45–02:00", title: "결과 공유와 다시 수정하는 법", description: "완성 주소를 공유하고 이후 혼자 수정하는 흐름을 익힙니다." },
    ],
    albumWorkshop: {
      eyebrow: "NEW · AI PHOTO ALBUM",
      title: "내 사진으로 만드는\nAI 애니메이션 앨범",
      description: "직접 준비한 사진을 따뜻한 지브리풍 손그림 애니메이션 이미지로 바꾸고, 정사각형·세로형·가로형 등 다른 포맷으로 확장한 뒤 하나의 앨범 사이트로 완성합니다.",
      outcomes: ["원본 사진과 AI 변환 사진", "정사각형·세로형·가로형 앨범 이미지", "휴대폰에서 넘겨보는 반응형 앨범", "가족과 친구에게 공유할 수 있는 실제 URL"],
      schedule: [
        { time: "00:00–00:15", title: "사진 선택과 앨범 주제 정하기", description: "직접 촬영했거나 사용 허락을 받은 사진 3–5장을 고르고 여행·가족·반려동물 등 앨범 주제를 정합니다." },
        { time: "00:15–00:40", title: "지브리풍 이미지로 변환", description: "원본의 인물과 배경 특징을 살리면서 따뜻한 손그림 애니메이션 감성으로 변환합니다." },
        { time: "00:40–01:00", title: "다른 포맷으로 다시 만들기", description: "같은 장면을 정사각형 표지, 세로형 카드, 가로형 배너에 맞게 재구성합니다." },
        { time: "01:00–01:25", title: "앨범 사이트 구성", description: "표지, 사진 순서, 제목과 짧은 설명을 넣어 모바일 앨범 화면을 만듭니다." },
        { time: "01:25–01:45", title: "화면 효과와 모바일 점검", description: "사진 전환과 카드 배치를 다듬고 휴대폰에서 잘 보이는지 확인합니다." },
        { time: "01:45–02:00", title: "앨범 주소 공개", description: "완성한 앨범을 실제 URL로 배포하고 공유 방법을 익힙니다." },
      ],
      safety: "본인이 촬영했거나 사용 허락을 받은 사진만 준비합니다. 다른 사람의 얼굴이 포함된 사진은 공개 전에 반드시 동의를 확인하고, 개인정보가 보이는 사진은 사용하지 않습니다.",
    },
    promptGuide: {
      eyebrow: "COPY & ASK CHATGPT",
      title: "ChatGPT에는 이렇게\n한 단계씩 질문하세요.",
      description: "한 번에 전부 요청하지 말고 결과를 확인한 다음 다음 프롬프트를 보내세요. 대괄호 안의 내용만 내 앨범에 맞게 바꾸면 됩니다.",
      items: [
        { step: "01", title: "먼저 계획표 만들기", purpose: "만들 내용을 작은 단계로 나눕니다.", prompt: "내가 가진 [여행/가족/반려동물] 사진 3~5장으로 온라인 앨범 사이트를 만들고 싶어. 초보자가 2시간 안에 완성할 수 있도록 작업 계획표를 만들어줘. 각 단계의 시간, 해야 할 일, 완성 결과를 표로 정리해줘." },
        { step: "02", title: "사진을 애니메이션풍으로 변환", purpose: "원본 사진의 특징을 유지한 변환 이미지를 만듭니다.", prompt: "첨부한 사진을 따뜻한 지브리풍 손그림 애니메이션 감성으로 바꿔줘. 인물의 표정과 자세, 배경의 핵심 특징은 유지하고 부드러운 색감과 자연광을 사용해줘. 사진 속 글자나 개인정보는 제거해줘." },
        { step: "03", title: "다른 포맷 만들기", purpose: "같은 이미지를 앨범의 여러 위치에 맞춥니다.", prompt: "방금 만든 이미지와 같은 분위기를 유지하면서 3가지 포맷으로 다시 만들어줘. 1) 정사각형 1:1 앨범 표지, 2) 세로형 4:5 사진 카드, 3) 가로형 16:9 메인 배너. 중요한 인물이나 피사체가 잘리지 않게 배치해줘." },
        { step: "04", title: "기술 조건 정하기", purpose: "수업 범위를 벗어나는 복잡한 기능을 막습니다.", prompt: "앨범 사이트의 기술 스펙은 HTML + CSS + JavaScript만 사용해줘. React, 데이터베이스, 로그인, 회원가입, 관리자 페이지, 서버 API 같은 백엔드는 사용하지 않아. 이미지와 설명은 프로젝트 폴더의 정적 파일로 관리하고, 별도 설치 없이 브라우저에서 실행되게 해줘." },
        { step: "05", title: "앨범 사이트 제작 요청", purpose: "확정한 이미지와 조건으로 실제 화면을 만듭니다.", prompt: "위 조건으로 반응형 사진 앨범 사이트를 만들어줘. 첫 화면에는 앨범 제목과 대표 이미지를 보여주고, 아래에는 사진 카드를 순서대로 배치해줘. 각 사진에는 짧은 설명을 넣고 클릭하면 크게 볼 수 있게 해줘. 모바일에서도 글자와 버튼이 잘 보이도록 만들어줘." },
        { step: "06", title: "마지막 검사 요청", purpose: "공개하기 전에 오류와 모바일 화면을 확인합니다.", prompt: "현재 앨범 사이트를 최종 점검해줘. 이미지 경로 오류, 모바일 화면 넘침, 너무 작은 글자, 작동하지 않는 버튼, 사진 대체 텍스트를 확인하고 수정해줘. 백엔드나 새로운 라이브러리는 추가하지 말고 HTML, CSS, JavaScript 범위 안에서 해결해줘." },
      ],
    },
    codexPromptGuide: {
      eyebrow: "COPY & ASK CODEX",
      title: "Codex에는 이렇게\n작업을 맡기세요.",
      description: "아래 문장을 위에서부터 하나씩 입력하세요. Codex가 답하거나 작업을 마칠 때마다 결과를 확인한 뒤 다음 문장으로 넘어가면 됩니다.",
      items: [
        { step: "01", title: "작업 소스 위치 확인", purpose: "엉뚱한 폴더를 수정하지 않도록 현재 위치부터 확인합니다.", prompt: "현재 열려 있는 작업공간의 절대 경로가 어디야? 홈페이지 소스가 들어 있는 폴더와 메인 페이지 파일, 스타일 파일의 위치를 찾아서 알려줘. 아직 파일은 수정하지 마." },
        { step: "02", title: "프로젝트 구조 이해", purpose: "자주 수정할 파일과 기술 구성을 먼저 파악합니다.", prompt: "이 프로젝트가 어떤 기술로 만들어졌는지 확인하고, 내가 주로 수정할 페이지·콘텐츠·스타일 파일을 초보자도 이해할 수 있게 정리해줘. 비밀키나 .env 내용은 출력하지 마." },
        { step: "03", title: "작업 범위 정하기", purpose: "원하지 않는 도구와 불필요한 변경을 막습니다.", prompt: "Sites 스킬은 사용하지 마. 현재 홈페이지의 기존 디자인과 다른 페이지는 유지하고, [수정할 내용]만 변경해줘. 시작하기 전에 변경할 파일과 작업 순서를 짧게 알려줘." },
        { step: "04", title: "페이지 수정 요청", purpose: "바꾸려는 내용과 지켜야 할 조건을 함께 전달합니다.", prompt: "1일 체험 페이지에 [추가할 내용]을 넣어줘. 모바일에서도 잘 보이게 하고, 메뉴와 버튼 링크가 실제 위치로 연결되게 해줘. 확인되지 않은 날짜·가격·후기는 만들지 마." },
        { step: "05", title: "오류와 화면 검사", purpose: "공개하기 전에 기능과 모바일 화면을 확인합니다.", prompt: "수정한 파일의 오류, 모바일 화면, 내부 링크, 접근성을 검사해줘. 문제가 있으면 고친 뒤 어떤 검사를 통과했는지 알려줘." },
        { step: "06", title: "GitHub에 파일 올리기", purpose: "검사를 통과한 변경만 안전하게 저장합니다.", prompt: "검사가 통과하면 이번에 수정한 파일만 Git에 추가하고 커밋한 뒤 GitHub main 브랜치에 올려줘. sample 폴더, .env, API 키, 비밀 파일은 커밋하지 마. 커밋 번호를 알려줘." },
        { step: "07", title: "운영 배포 확인", purpose: "GitHub 업로드에서 멈추지 않고 실제 사이트까지 확인합니다.", prompt: "GitHub 업로드 후 autosites-jd3d Vercel 운영 배포가 SUCCESS가 될 때까지 확인해줘. 운영 주소에서 변경 내용이 보이는지 확인하고 URL과 남은 경고를 알려줘. 중복 프로젝트 autosites는 건드리지 마." },
      ],
      note: "GitHub 업로드는 검사 통과 후 진행합니다. 현재 저장소와 브랜치를 다시 확인하고, 비밀 파일은 절대 올리지 않습니다.",
    },
    preparation: ["개인 노트북", "노트북 충전기", "사용 가능한 이메일 계정", "소개하고 싶은 주제 한 가지"],
    note: "체험 일정과 참가비는 확정된 회차만 당근 채팅으로 안내합니다.",
  },
  workflow: {
    eyebrow: "HOW IT WORKS",
    title: "말 한마디에서\n실제 홈페이지까지",
    description: "말로 설명하고 → AI가 만들고 → 직접 수정하고 → 실제 인터넷에 배포합니다.",
    steps: [
      { number: "01", title: "아이디어를 말합니다", description: "“골프 모임 회원들이 일정을 확인하고 참석 여부를 선택할 수 있는 홈페이지 만들어줘.”" },
      { number: "02", title: "AI가 홈페이지를 만듭니다", description: "Codex가 구조를 만들고 디자인, 모바일 대응과 실제 코드를 구현합니다." },
      { number: "03", title: "원하는 대로 수정합니다", description: "“버튼을 더 크게”, “모바일에서 보기 좋게”, “회원가입 기능을 추가해줘”처럼 다시 요청합니다." },
      { number: "04", title: "실제 인터넷에 배포합니다", description: "GitHub에 안전하게 저장하고 Vercel을 통해 누구나 접속할 수 있는 URL로 공개합니다." },
    ],
    result: "결과물은 설명서가 아니라 실제 접속 가능한 홈페이지입니다.",
  },
  journey: ["아이디어", "AI 제작", "수정", "배포"],
  audience: {
    eyebrow: "FOR YOU",
    title: "이런 분께 추천합니다",
    items: [
      { title: "홈페이지를 만들고 싶은 사람", description: "아이디어는 있지만 개발자를 찾기 부담스러운 사람" },
      { title: "코딩을 배우다 지친 사람", description: "문법 공부보다 실제 결과물을 만들고 싶은 사람" },
      { title: "사업을 준비하는 사람", description: "내 사업을 소개할 홈페이지가 필요한 사람" },
      { title: "AI를 제대로 활용하고 싶은 사람", description: "ChatGPT를 넘어 실제 서비스를 만들고 싶은 사람" },
      { title: "포트폴리오가 필요한 사람", description: "취업이나 창업을 위해 실제 결과물이 필요한 사람" },
      { title: "새로운 것을 직접 만들고 싶은 사람", description: "개발 경험 없이도 AI와 하나씩 완성하고 싶은 사람" },
    ],
  },
  technology: {
    eyebrow: "YOUR AI BUILD TEAM",
    title: "도구는 어려운 이름보다\n역할만 이해하면 됩니다.",
    items: [
      { name: "ChatGPT", role: "아이디어와 기획", description: "무엇을 만들지 함께 정리합니다." },
      { name: "Codex", role: "실제 코드 제작", description: "말로 요청한 내용을 코드로 구현합니다." },
      { name: "GitHub", role: "프로젝트 저장소", description: "만든 홈페이지 코드를 안전하게 관리합니다." },
      { name: "Vercel", role: "인터넷 배포", description: "완성된 홈페이지를 실제 URL로 공개합니다." },
      { name: "Supabase", role: "필요할 때 데이터 저장", description: "회원가입, 로그인, 게시판 기능을 확장할 때 사용합니다." },
    ],
  },
  comparison: {
    eyebrow: "BEFORE / AFTER",
    title: "예전에는 이렇게 만들었습니다",
    before: { label: "기존 방식", flow: "기획 → 디자인 → 코딩 → 개발 → 서버 → 배포", description: "시간이 오래 걸리고 전문적인 지식이 필요했습니다." },
    after: { label: "AI 시대", flow: "아이디어 → AI 제작 → 수정 → 배포", description: "아이디어와 AI 활용 능력이 중요해졌습니다." },
  },
  projects: {
    eyebrow: "PROJECT IDEAS",
    title: "무엇을 만들 수 있나요?",
    description: "주제와 목적을 말하면 필요한 정보 구조와 화면부터 함께 만듭니다.",
    items: [
      { type: "BUSINESS", title: "사업 홈페이지", description: "회사 · 개인사업자 · 브랜드", accent: "상담 요청" },
      { type: "COMMERCE", title: "쇼핑몰", description: "상품 소개 · 판매 · 주문", accent: "상품 보기" },
      { type: "PORTFOLIO", title: "포트폴리오", description: "개발자 · 디자이너 · 프리랜서", accent: "프로젝트" },
      { type: "COMMUNITY", title: "커뮤니티", description: "모임 · 스터디 · 동호회", accent: "참여하기" },
      { type: "BOOKING", title: "예약 서비스", description: "골프 · 레스토랑 · 클래스 · 상담", accent: "예약하기" },
      { type: "AI SERVICE", title: "AI 서비스", description: "추천 · 검색 · 자동화 · 콘텐츠 생성", accent: "AI 시작" },
    ],
  },
  classPreview: {
    eyebrow: "4-WEEK PRACTICAL CLASS",
    title: "4주 동안 하나의\n실제 홈페이지를 완성합니다.",
    weeks: [
      { week: "1주차", title: "막막했던 도구를 내 노트북에 연결" },
      { week: "2주차", title: "머릿속 아이디어를 첫 화면으로 제작" },
      { week: "3주차", title: "다른 사람에게 보여줄 주소로 배포" },
      { week: "4주차", title: "혼자 수정하고 다시 배포하는 흐름 완성" },
    ],
    promise: "4주 후에는 ‘배웠습니다’가 아니라 ‘제가 만든 홈페이지가 있습니다’라고 말할 수 있게 합니다.",
    action: { label: "내가 따라갈 수 있는지 물어보기", href: recruitmentUrl },
  },
  whyNow: {
    eyebrow: "WHY START NOW",
    title: "계속 미루면 홈페이지는\n아이디어로만 남습니다.",
    description: "혼자 시작하면 설치와 배포에서 멈추기 쉽습니다. 이번 4주에는 설명을 듣는 데서 끝내지 않고, 실제로 접속되는 내 홈페이지 주소까지 함께 완성합니다.",
    reasons: [
      { number: "01", title: "최대 8명 소규모 실습", description: "내 화면을 보며 막힌 지점을 질문하고 바로 해결합니다." },
      { number: "02", title: "내 주제로 직접 제작", description: "공통 예제를 따라 하는 대신 사업·모임·포트폴리오처럼 나에게 필요한 홈페이지를 만듭니다." },
      { number: "03", title: "실제 URL까지 완성", description: "기획만 배우는 수업이 아니라 GitHub 저장과 Vercel 배포까지 직접 끝냅니다." },
      { number: "04", title: "2기는 10월 10일 시작", description: "10월 10일부터 31일까지 매주 토요일, 4주 동안 진행합니다. 당근 채팅에서 남은 자리를 확인할 수 있습니다." },
    ],
    result: "4주 뒤에는 ‘배웠습니다’가 아니라 ‘제가 만든 홈페이지가 있습니다’라고 말하게 됩니다.",
    note: "확인되지 않은 마감 안내는 하지 않습니다. 당근 채팅에서 실제 남은 자리와 참여 가능 일정을 안내합니다.",
    action: { label: "남은 자리와 준비물 확인하기", href: recruitmentUrl },
  },
  pricing: {
    eyebrow: "STARTER CLASS",
    title: "처음 시작하는 사람을 위한 실전 클래스",
    included: ["AI 홈페이지 제작", "Codex 활용법", "GitHub 사용법", "Vercel 배포", "실제 프로젝트 제작", "모바일 최적화", "프로젝트 완성까지 실습"],
    action: { label: "만들고 싶은 홈페이지 물어보기", href: recruitmentUrl },
  },
  setup: {
    eyebrow: "BEFORE YOU START",
    title: "처음 한 번만,\n작업 환경을 연결합니다.",
    description: "수업용 Google 계정과 Chrome 프로필을 먼저 통일한 뒤 ChatGPT·Codex, Git·GitHub, Vercel을 연결합니다. Supabase는 로그인이나 데이터 저장이 필요할 때만 추가합니다.",
    requiredLabel: "필수 준비",
    optionalLabel: "선택 기능",
    rolesTitle: "각 서비스는 이런 역할을 합니다.",
    rolesDescription: "코드를 만드는 도구, 저장하는 공간, 실행하는 서버와 데이터를 보관하는 데이터베이스를 나눠 연결합니다.",
    roles: [
      { name: "Codex", role: "제작·수정", description: "채팅 요청을 이해해 React·Next.js 코드와 홈페이지 내용을 수정하고 검사합니다.", status: "작업 도구" },
      { name: "Git", role: "변경 이력", description: "수정된 파일의 버전을 기록하고 이전 정상 상태로 되돌릴 수 있게 합니다.", status: "필수" },
      { name: "GitHub", role: "코드 저장", description: "React·Next.js 소스코드와 Git 변경 이력을 온라인 저장소에 보관합니다.", status: "필수" },
      { name: "Vercel", role: "프론트·백엔드 배포", description: "화면과 Next.js API를 운영 서버에 배포하고 도메인·SSL·자동 배포를 담당합니다.", status: "필수" },
      { name: "Supabase", role: "로그인·DB·CRUD", description: "회원 인증과 데이터 생성·조회·수정·삭제, 파일 저장 기능을 제공합니다.", status: "필요할 때" },
    ],
    flow: ["Codex 수정", "Git 기록", "GitHub 저장", "Vercel 배포", "Supabase 데이터"],
    browserRule: {
      title: "계정과 브라우저를 섞지 마세요.",
      description: "Chrome과 Edge에 서로 다른 계정이 로그인되어 있으면 GitHub·Vercel 인증 때 다른 사용자를 승인하기 쉽습니다. 수업에서는 하나의 Google 계정과 하나의 Chrome 프로필을 처음부터 끝까지 사용합니다.",
      checks: ["Chrome 오른쪽 위 프로필에서 수업용 이메일 확인", "GitHub·Vercel 인증 화면도 같은 Chrome에서 열기", "Edge나 다른 이메일이 보이면 승인 전에 창을 닫고 계정 확인"],
    },
    steps: [
      { number: "01", title: "Google 계정 만들기 · Chrome 통일", description: "수업에 사용할 Google 계정 하나를 정하고 Chrome에 로그인합니다. 이후 웹 인증은 다른 브라우저와 섞지 않고 이 Chrome 프로필에서 진행합니다.", checklist: ["수업용 Google 계정 생성 또는 사용할 계정 결정", "Chrome 설치 후 오른쪽 위 프로필에 해당 계정 로그인", "Windows 기본 브라우저를 Chrome으로 설정", "프로필 아이콘에 표시된 이메일 주소 확인", "수업 중 Edge에서 다른 계정으로 인증하지 않기"], action: { label: "Google 계정 만들기", href: "https://accounts.google.com/signup" } },
      { number: "02", title: "ChatGPT 가입 · Codex 준비", description: "수업용 계정으로 ChatGPT에 로그인하고 홈페이지 폴더를 Codex에서 엽니다.", checklist: ["Chrome에서 ChatGPT 계정 생성과 로그인", "ChatGPT 데스크톱 앱 설치", "프로젝트 폴더 열기", "Codex를 선택해 첫 요청 보내기"], action: { label: "공식 시작 안내", href: "https://learn.chatgpt.com/docs/quickstart" } },
      { number: "03", title: "Git 설치 · 사용자 설정", description: "Windows에 Git을 설치하고 터미널을 다시 연 뒤 이름과 이메일을 등록합니다.", checklist: ["Git for Windows 설치", "git --version으로 설치 확인", "커밋 작성자 이름·이메일 설정"], commands: ["winget install --id Git.Git -e --source winget", "git --version", "git config --global user.name \"YOUR_NAME\"", "git config --global user.email \"YOUR_EMAIL\""], action: { label: "Git 설치 안내", href: "https://git-scm.com/install/windows" } },
      { number: "04", title: "GitHub 가입 · 저장소 생성", description: "Chrome에서 GitHub에 가입하고 빈 저장소를 만든 뒤 로컬 홈페이지의 main 브랜치를 연결해 Push합니다.", checklist: ["Chrome의 수업용 계정 확인 후 GitHub 가입", "브라우저 인증 창에 표시된 GitHub 사용자 확인", "New repository에서 빈 저장소 생성", "origin 연결 후 main Push"], commands: ["git init -b main", "git add .", "git commit -m \"first commit\"", "git remote add origin https://github.com/USERNAME/REPOSITORY.git", "git push -u origin main"], action: { label: "저장소 연결 안내", href: "https://docs.github.com/en/migrations/importing-source-code/using-the-command-line-to-import-source-code/adding-locally-hosted-code-to-github" } },
      { number: "05", title: "Vercel 가입 · 자동 배포", description: "같은 Chrome에서 GitHub 계정으로 Vercel에 가입하고 저장소를 Import하면 main Push마다 운영 주소가 갱신됩니다.", checklist: ["Chrome에서 현재 GitHub 사용자 다시 확인", "GitHub로 Vercel 가입 및 권한 승인", "Add New → Project에서 GitHub 저장소 Import", "Framework Preset: Next.js 확인", "Deploy 후 READY와 운영 URL 확인"], action: { label: "Git 배포 안내", href: "https://vercel.com/docs/git" } },
      { number: "06", title: "Supabase 가입 · 계정 확인", description: "같은 Chrome에서 GitHub 계정으로 Supabase에 가입합니다. 이 단계에서는 프로젝트나 데이터베이스를 만들지 않고 대시보드 로그인까지만 확인합니다.", checklist: ["같은 Chrome 프로필에서 Supabase 대시보드 열기", "Sign in with GitHub 선택", "인증 화면의 GitHub 사용자 이름과 이메일 확인", "GitHub 권한 요청 내용을 확인한 뒤 승인", "Supabase 대시보드가 열리는지 확인"], action: { label: "Supabase 가입·대시보드 열기", href: "https://supabase.com/dashboard" } },
    ],
    optional: {
      number: "07", title: "Supabase 프로젝트 연결 — 필요할 때만", description: "가입 이후 회원 로그인, 문의 저장, 게시판처럼 데이터 기능이 필요한 프로젝트에서만 진행합니다.",
      checklist: ["New project에서 조직·프로젝트 이름 입력", "Database 비밀번호를 만들고 공개되지 않는 곳에 별도 보관", "가까운 Region을 선택하고 Create new project 실행", "Connect 화면에서 Project URL·Publishable key 확인", ".env.local과 Vercel 환경변수에 같은 값 등록", "테이블 생성 후 RLS 보안 정책 점검"],
      env: ["NEXT_PUBLIC_SUPABASE_URL=...", "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=..."], warning: "Secret·service role 키는 NEXT_PUBLIC에 넣거나 GitHub에 올리면 안 됩니다.",
      action: { label: "Next.js 연결 안내", href: "https://supabase.com/docs/guides/getting-started/quickstarts/nextjs" },
    },
  },
  showcase: {
    eyebrow: "ONE WORKFLOW, MANY RESULTS",
    title: "주제가 달라지면,\n결과도 달라집니다.",
    description: "같은 템플릿에 문구만 바꾸는 방식이 아닙니다. 업종과 고객, 원하는 분위기에 맞춰 정보 구조부터 색상과 화면 표현까지 함께 조정합니다.",
    imageAlt: "카페, 전문 컨설팅, 크리에이티브 포트폴리오 홈페이지가 데스크톱과 모바일 화면에 적용된 예시",
    cases: [
      { type: "CAFE", title: "따뜻한 로컬 카페", request: "베이지와 짙은 갈색으로 편안한 매장 분위기를 보여줘.", result: "메뉴 · 공간 소개 · 방문 CTA" },
      { type: "STUDIO", title: "신뢰감 있는 전문 스튜디오", request: "서비스 강점이 명확하고 상담으로 자연스럽게 이어지게 해줘.", result: "서비스 · 업무 방식 · 상담 CTA" },
      { type: "PORTFOLIO", title: "선명한 크리에이티브 포트폴리오", request: "작업물이 먼저 보이고 개성이 강한 화면으로 바꿔줘.", result: "프로젝트 · 소개 · 협업 CTA" },
    ],
  },
  examples: {
    eyebrow: "PROMPT EXAMPLES",
    title: "이렇게 요청하면 됩니다.",
    items: [
      "카페 홈페이지로 바꾸고 베이지와 짙은 갈색을 사용해줘.",
      "서비스 소개 아래에 가격표와 상담 신청 버튼을 추가해줘.",
      "대표 이미지를 교체하고 모바일 화면의 글자 크기를 조정해줘.",
      "오류를 검사한 다음 GitHub와 Vercel에 배포해줘.",
    ],
  },
  deployment: {
    eyebrow: "SAFE DEPLOYMENT",
    title: "바로 올리지 않고,\n확인한 뒤 배포합니다.",
    points: [
      { title: "변경 범위 확인", description: "기존 작업과 디자인을 보존하면서 요청한 부분만 수정합니다." },
      { title: "품질 검사", description: "코드 오류와 빌드 실패 여부를 확인하고 통과한 변경만 저장합니다." },
      { title: "배포 이력", description: "GitHub 커밋과 Vercel 배포가 연결되어 언제든 변경 내역을 확인할 수 있습니다." },
      { title: "운영 확인", description: "배포 상태가 READY인지 확인하고 실제 주소에서 최신 화면이 열리는지 검사합니다." },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    title: "자주 묻는 질문",
    items: [
      { question: "코딩을 전혀 몰라도 가능한가요?", answer: "가능합니다. AI에게 원하는 결과를 자연어로 설명하고 결과를 확인하면서 수정하는 방식으로 진행합니다." },
      { question: "React를 꼭 알아야 하나요?", answer: "처음부터 React를 요구하지 않습니다. 프로젝트 수준에 맞춰 필요한 기술을 단계적으로 사용합니다." },
      { question: "홈페이지를 실제 인터넷에 올릴 수 있나요?", answer: "가능합니다. GitHub와 Vercel을 활용해 실제 URL로 배포하는 것까지 경험합니다." },
      { question: "완성된 홈페이지를 나중에 수정할 수 있나요?", answer: "가능합니다. AI에게 원하는 수정 내용을 설명하면서 계속 개선할 수 있습니다." },
      { question: "어떤 홈페이지를 만들 수 있나요?", answer: "회사 홈페이지, 개인 홈페이지, 포트폴리오, 모임, 쇼핑몰, 예약 서비스 등 다양한 형태로 확장할 수 있습니다." },
      { question: "AI가 모든 것을 알아서 해주나요?", answer: "아닙니다. AI에게 정확하게 요구하고 결과를 확인하고 수정하는 능력을 배우는 것이 클래스의 핵심입니다." },
    ],
  },
  finalCta: {
    eyebrow: "ASK BEFORE YOU APPLY",
    title: "바로 신청하지 않아도 괜찮습니다.\n내가 따라갈 수 있을지 먼저 물어보세요.",
    description: "현재 실력, 만들고 싶은 홈페이지와 준비물을 알려주시면 참여 가능한 일정과 남은 자리를 안내합니다.",
    action: { label: "당근에서 편하게 물어보기", href: recruitmentUrl },
  },
  footer: {
    description: "Codex 채팅 기반 홈페이지 제작·수정·배포 워크플로",
    repository: "https://github.com/cursaman/autosites",
  },
} as const;

export const courseContent = {
  hero: {
    eyebrow: "BEGINNER-FRIENDLY · 4-WEEK PRACTICAL COURSE",
    title: "4주 뒤, 직접 만든\n홈페이지 주소를 가져가세요.",
    description: "계속 미뤄온 아이디어를 이번에는 실제 주소로 완성하세요. 코드를 외우는 대신 Codex에 설명하고 직접 수정한 뒤, GitHub와 Vercel로 공개하는 전 과정을 함께 끝냅니다.",
    facts: ["4주", "매주 토요일", "오후 6시–8시", "총 8시간", "최대 8명"],
  },
  promise: {
    eyebrow: "WHY THIS COURSE",
    title: "혼자서는 막히는 지점을\n수업에서 함께 넘습니다.",
    concerns: [
      { question: "무엇부터 시작해야 할지 모르겠어요.", answer: "설치부터 첫 요청까지 같은 화면을 보며 함께 시작합니다." },
      { question: "AI가 만든 코드를 믿어도 될까요?", answer: "결과를 확인하고 오류를 검사하고 다시 요청하는 방법을 배웁니다." },
      { question: "만들어도 인터넷에 올리지 못할 것 같아요.", answer: "GitHub 저장부터 Vercel 운영 주소 확인까지 직접 실습합니다." },
    ],
    deliverablesTitle: "4주 뒤 내 손에 남는 것",
    deliverables: [
      { number: "01", title: "내 주제의 반응형 홈페이지", description: "가게, 서비스, 포트폴리오 등 자신에게 필요한 내용으로 제작합니다." },
      { number: "02", title: "GitHub 코드 저장소", description: "모든 작업 이력을 내 계정에 안전하게 보관합니다." },
      { number: "03", title: "실제로 열리는 운영 URL", description: "휴대폰이나 다른 사람의 컴퓨터에서도 접속할 수 있게 배포합니다." },
      { number: "04", title: "다시 수정하고 배포하는 방법", description: "수업 이후에도 Codex와 대화하며 스스로 운영할 수 있습니다." },
    ],
  },
  instructor: {
    eyebrow: "YOUR GUIDE",
    name: "AutoSites 운영자",
    title: "채팅 요청부터 실제 배포까지 함께합니다.",
    description: "코드를 대신 외워주는 수업이 아니라, Codex에 원하는 결과를 설명하고 직접 확인·수정한 뒤 GitHub와 Vercel로 공개하는 과정을 같은 화면을 보며 진행합니다.",
    proof: "지금 보고 있는 AutoSites 홈페이지도 같은 방식으로 제작하고 수정하며 운영하고 있습니다.",
    support: [
      { icon: "🧭", title: "처음 설정부터", description: "ChatGPT·Codex 준비, Git 설치와 GitHub 저장소 연결을 함께 확인합니다." },
      { icon: "🛠️", title: "막힌 화면에서 바로", description: "오류 메시지와 현재 화면을 함께 보고 다음 요청을 어떻게 작성할지 안내합니다." },
      { icon: "🚀", title: "실제 URL 확인까지", description: "Vercel 배포가 끝났다는 표시가 아니라 휴대폰에서 운영 주소가 열리는 것까지 확인합니다." },
    ],
  },
  progress: {
    eyebrow: "COHORT 01",
    title: "1기 4주 과정을 수료했습니다.",
    description: "8월 29일부터 9월 19일까지 4주간의 수업을 모두 완료했습니다. 홈페이지 제작부터 수정, GitHub 저장과 Vercel 배포까지 전 과정을 함께 마쳤습니다.",
    updatedAt: "2026. 09. 21 기준",
    sessions: [
      { week: "1주차", date: "8월 29일", topic: "웹과 작업환경 이해", status: "완료" },
      { week: "2주차", date: "9월 5일", topic: "랜딩페이지 제작", status: "완료" },
      { week: "3주차", date: "9월 12일", topic: "GitHub·Vercel 배포", status: "완료" },
      { week: "4주차", date: "9월 19일", topic: "수정과 운영", status: "완료" },
    ],
  },
  records: {
    eyebrow: "CLASS RECORDS",
    title: "수업이 끝날 때마다 기록합니다.",
    description: "완료된 수업에서 실제로 다룬 내용과 다음 단계에 필요한 결과물을 공개합니다. 수강생 개인정보는 포함하지 않습니다.",
    items: [
      { week: "1주차", date: "2026. 08. 29", title: "웹과 작업환경 준비 완료", summary: "웹사이트의 기본 구조를 이해하고 Codex, Git, GitHub, Vercel이 각각 어떤 역할을 하는지 확인했습니다.", completed: ["ChatGPT·Codex 작업 방식 이해", "Git 설치와 작성자 설정", "GitHub 저장소 생성", "첫 커밋과 Push 실습"], next: "2주차에는 자신의 홈페이지 주제와 고객을 정하고 반응형 랜딩페이지를 제작합니다." },
    ],
  },
  audience: ["코딩을 처음 접하는 분", "직접 홈페이지를 만들고 싶은 분", "소상공인과 1인 사업자", "제작 이후 수정과 배포까지 배우고 싶은 분"],
  apiWorkshop: {
    eyebrow: "SEPARATE WORKSHOP PLAN",
    title: "AI API 연결을 위한 별도 2시간 실습 계획표",
    description: "4주 홈페이지 과정과 구분된 별도 실습 계획입니다. API가 처음인 분도 완성된 예제를 먼저 실행하고, 키 설정부터 화면 연결과 오류 해결까지 한 단계씩 따라갑니다.",
    goal: "입력 → AI 요청 → 결과 출력이 작동하는 나만의 프로그램",
    resources: [
      { order: "1단계", type: "MD", difficulty: "입문", audience: "API 연결이 처음인 분", title: "AI API 실습 안내서", description: "설치, API 키 설정, 실행 순서, 코드 흐름과 자주 발생하는 오류를 정리했습니다.", href: "/downloads/AI-API-실습-안내서.md", fileName: "AI-API-실습-안내서.md" },
      { order: "2단계", type: "ZIP", difficulty: "입문", audience: "첫 AI 응답을 직접 받아볼 분", title: "초보자용 샘플 소스", description: "Node.js 서버, 질문 화면, 환경변수 예제와 실행 README가 포함되어 있습니다.", href: "/downloads/ai-api-workshop-sample.zip", fileName: "ai-api-workshop-sample.zip" },
      { order: "3단계", type: "PDF", difficulty: "입문 이후", audience: "전체 제작 흐름을 순서대로 공부할 분", title: "14일 웹서비스 제작 교재", description: "local-food 프로젝트를 화면, API, 데이터베이스, 로그인, 지도, AI와 배포 순서로 설명한 22쪽 교재입니다.", href: "/downloads/AI와_함께_14일_웹서비스_만들기.pdf", fileName: "AI와_함께_14일_웹서비스_만들기.pdf" },
      { order: "4단계", type: "ZIP", difficulty: "실전", audience: "Next.js·API·DB까지 확장할 분", title: "local-food 완성 패키지", description: "Next.js 소스, PRD·API·DB 문서, Supabase 스키마와 14일 체크리스트가 포함된 실전 프로젝트입니다.", href: "/downloads/local-food-complete-package.zip", fileName: "local-food-complete-package.zip" },
    ],
    schedule: [
      { time: "00:00–00:10", title: "완성 예제와 API 흐름 이해", result: "오늘 만들 결과를 먼저 확인합니다." },
      { time: "00:10–00:25", title: "개발 환경 확인", result: "예제 프로젝트를 내 노트북에서 실행합니다." },
      { time: "00:25–00:40", title: "API 키 안전하게 설정", result: "환경변수에 키를 저장하고 보안 원칙을 익힙니다." },
      { time: "00:40–01:00", title: "첫 AI 응답 받기", result: "준비된 코드로 API 요청과 응답을 확인합니다." },
      { time: "01:00–01:10", title: "휴식과 개별 점검", result: "막힌 설정을 함께 해결합니다." },
      { time: "01:10–01:30", title: "입력 화면 연결", result: "입력창·버튼·결과 영역을 연결합니다." },
      { time: "01:30–01:45", title: "내 프로그램으로 변형", result: "프롬프트를 바꿔 원하는 기능을 만듭니다." },
      { time: "01:45–01:55", title: "자주 만나는 오류 해결", result: "401·429·환경변수 오류를 읽고 해결합니다." },
      { time: "01:55–02:00", title: "결과 공유와 다음 과제", result: "혼자 다시 실행할 수 있는지 확인합니다." },
    ],
    principles: ["빈 프로젝트 대신 완성 예제부터 실행", "API 키는 코드와 GitHub에 저장하지 않기", "코드 암기보다 요청과 응답 흐름 이해", "디자인보다 작동하는 한 가지 기능 완성"],
  },
  curriculum: [
    { week: "01", title: "웹과 작업환경 이해", objective: "홈페이지 제작에 필요한 도구의 역할을 이해하고 개인 작업환경을 준비합니다.", status: "완료", items: ["웹사이트가 작동하는 방법", "Codex·Git·GitHub·Vercel 역할", "Git 설치와 저장소 생성"], schedule: [{ time: "18:00", lesson: "웹사이트와 바이브코딩 이해" }, { time: "18:25", lesson: "Codex·GitHub·Vercel 역할" }, { time: "18:50", lesson: "ChatGPT·Git 설치와 설정" }, { time: "19:25", lesson: "GitHub 저장소 생성·첫 Push" }], result: "작업환경과 GitHub 저장소" },
    { week: "02", title: "랜딩페이지 제작", objective: "만들고 싶은 홈페이지를 설명하고 반응형 랜딩페이지를 완성합니다.", status: "완료", items: ["홈페이지 주제와 고객 정하기", "Codex 요청문 작성", "문구·색상·모바일 화면 수정"], schedule: [{ time: "18:00", lesson: "업종·고객·목표 정하기" }, { time: "18:25", lesson: "홈페이지 요청문 작성" }, { time: "18:50", lesson: "Codex로 화면 제작" }, { time: "19:30", lesson: "모바일·문구·색상 수정" }], result: "반응형 랜딩페이지" },
    { week: "03", title: "실제 홈페이지 배포", objective: "제작한 코드를 안전하게 저장하고 누구나 접속할 수 있는 주소로 공개합니다.", status: "완료", items: ["Git 변경사항 저장", "GitHub main Push", "Vercel 연결과 운영 URL 확인"], schedule: [{ time: "18:00", lesson: "저장과 배포의 차이" }, { time: "18:20", lesson: "Git 상태 확인·커밋" }, { time: "18:50", lesson: "GitHub main Push" }, { time: "19:20", lesson: "Vercel 연결·운영 검사" }], result: "공개된 홈페이지 주소" },
    { week: "04", title: "수정과 운영", objective: "운영 홈페이지를 다시 수정하고 검사와 재배포를 스스로 반복합니다.", status: "완료", items: ["Codex로 내용 다시 수정", "오류 검사와 자동 재배포", "도메인·Supabase·CRUD 이해"], schedule: [{ time: "18:00", lesson: "실제 수정 요청 작성" }, { time: "18:30", lesson: "빌드 검사·오류 해결" }, { time: "19:00", lesson: "자동 재배포와 운영 확인" }, { time: "19:30", lesson: "도메인·로그인·CRUD 이해" }], result: "스스로 운영하는 작업 흐름" },
  ],
  outcomes: ["Codex로 홈페이지 제작·수정", "Git으로 변경 이력 관리", "GitHub에 소스코드 보관", "Vercel로 화면과 API 배포", "로그인·데이터베이스가 필요한 시점 구분"],
  completion: {
    eyebrow: "RESULTS & NEXT COHORT",
    title: "1기의 과정이\n다음 기수의 안내가 됩니다.",
    description: "1기는 4주간의 수업을 모두 마쳤습니다. 공개 동의를 받은 결과물과 후기만 확인해 소개합니다.",
    status: "1기 4주 과정 수료 완료",
    resultSlots: [
      { title: "MOVIEBOX", timing: "1기 수강생 작품 · 운영 중", description: "인기 영화, 현재 상영작, 개봉 예정작과 영화 상세정보를 탐색할 수 있는 반응형 영화 정보 서비스입니다.", href: "https://bb-movie-rho.vercel.app/", actionLabel: "수강생 작품 보기" },
      { title: "수강 후기", timing: "공개 동의 확인 후", description: "실명 대신 닉네임 사용이 가능하며 공개에 동의한 후기만 게시합니다." },
      { title: "교육 현장 기록", timing: "공개 동의 확인 후", description: "참여자의 얼굴이나 개인정보가 노출되지 않도록 확인한 사진만 사용합니다." },
    ],
    privacy: "결과물·후기·사진 공개 여부는 교육 참여와 별개이며, 동의하지 않아도 불이익이 없습니다.",
  },
  nextCohort: {
    label: "2기 모집 안내",
    title: "2기는 10월 10일 토요일에 시작합니다.",
    description: "2026년 10월 10일, 17일, 24일, 31일에 매주 토요일 오후 6시부터 8시까지 4주 동안 진행합니다. 당근 채팅으로 남은 자리와 준비사항을 확인해 주세요.",
    schedule: "2026. 10. 10–10. 31 · 매주 토요일",
    actionLabel: "2기 남은 자리 문의하기",
  },
  fee: { amount: "80,000원", label: "4주 전체 교육비", description: "별도의 장소 이용료 없이 4주 수업과 실습 환경이 모두 포함됩니다.", included: ["주 1회 2시간 · 총 8시간 실습", "커피긱스 2층 8인룸", "수업용 빔프로젝터", "매회 커피 제공"] },
  venue: {
    name: "커피긱스 2층 8인룸", address: "부산광역시 연제구 교대로24번길 7", description: "부산교육대학교 인근 · 주차 가능", time: "매주 토요일 오후 6시–8시",
    details: ["오후 6시 정시 시작", "2층 8인룸으로 이동", "건물 주차 가능", "Wi-Fi는 현장에서 안내"],
    mapUrl: "https://map.kakao.com/link/search/부산광역시%20연제구%20교대로24번길%207",
  },
  preparation: ["개인 노트북", "노트북 충전기", "사용 가능한 이메일 계정"],
  recruitment: {
    title: "최대 8명의 소규모 실습",
    description: "혼자 준비하다 설치와 배포에서 멈추지 않도록 최대 8명과 함께 끝까지 실습합니다. 당근 모임에서 실제 남은 자리와 참여 가능한 일정을 먼저 확인해 주세요.",
    status: "당근에서 모집 중",
    capacity: "정원 8명 · 자리 확인 후 신청 확정",
    steps: [
      { number: "01", title: "당근 모임 열기", description: "부산 사직동 바이브코딩 모임 페이지로 이동합니다." },
      { number: "02", title: "채팅으로 문의", description: "참여 가능한 날짜와 만들고 싶은 홈페이지를 알려주세요." },
      { number: "03", title: "자리 확인", description: "남은 자리와 수업 준비사항을 채팅으로 안내받습니다." },
      { number: "04", title: "신청 확정", description: "확정 안내를 받으면 오후 6시 수업에 참여합니다." },
    ],
    inquiryItems: ["이름 또는 당근 닉네임", "참여 가능한 수업 날짜", "개인 노트북 보유 여부", "만들고 싶은 홈페이지 주제"],
    privacy: "이 페이지에서는 이름·전화번호·이메일을 수집하거나 공개하지 않습니다. 교육 운영에 필요한 연락은 당근 채팅으로 진행합니다.",
    action: { label: "당근에서 남은 자리 문의하기", href: recruitmentUrl },
  },
} as const;
