export const siteContent = {
  brand: "AutoSites",
  navigation: [
    { label: "AI 홈페이지", href: "#top" },
    { label: "제작 과정", href: "#process" },
    { label: "프로젝트", href: "#projects" },
    { label: "4주 클래스", href: "#class" },
    { label: "FAQ", href: "#faq" },
  ],
  hero: {
    eyebrow: "AI WEBSITE BUILDER",
    title: "코딩 없이\nAI로 홈페이지 하나 만들어보세요.",
    description: "아이디어만 있으면 됩니다. ChatGPT + Codex + GitHub + Vercel을 활용해 실제로 작동하는 홈페이지를 만들고 인터넷에 배포합니다.",
    primaryAction: { label: "직접 만들어보기", href: "/education/join.html" },
    secondaryAction: { label: "제작 과정 보기", href: "#process" },
    note: "HTML · CSS · JavaScript를 몰라도 시작할 수 있습니다.",
  },
  workflow: {
    eyebrow: "HOW IT WORKS",
    title: "말 한마디에서\n실제 홈페이지까지",
    description: "말로 설명하고 → AI가 만들고 → 직접 수정하고 → 실제 인터넷에 배포합니다.",
    steps: [
      { number: "01", title: "아이디어를 말합니다", description: "“골프 모임 회원들이 일정을 확인하고 참석 여부를 선택할 수 있는 홈페이지 만들어줘.”" },
      { number: "02", title: "AI가 홈페이지를 만듭니다", description: "Codex가 구조를 만들고 디자인, 모바일 대응과 실제 코드를 구현합니다." },
      { number: "03", title: "원하는 대로 수정합니다", description: "“버튼을 더 크게”, “모바일에서 보기 좋게”, “회원가입 기능을 추가해줘”처럼 다시 요청합니다." },
      { number: "04", title: "실제 인터넷에 배포합니다", description: "GitHub에 안전하게 저장하고 Vercel을 통해 누구나 접속할 수 있는 URL로 공개합니다." },
    ],
    result: "결과물은 설명서가 아니라 실제 접속 가능한 홈페이지입니다.",
  },
  journey: ["아이디어", "AI 제작", "수정", "배포"],
  audience: {
    eyebrow: "FOR YOU",
    title: "이런 분께 추천합니다",
    items: [
      { title: "홈페이지를 만들고 싶은 사람", description: "아이디어는 있지만 개발자를 찾기 부담스러운 사람" },
      { title: "코딩을 배우다 지친 사람", description: "문법 공부보다 실제 결과물을 만들고 싶은 사람" },
      { title: "사업을 준비하는 사람", description: "내 사업을 소개할 홈페이지가 필요한 사람" },
      { title: "AI를 제대로 활용하고 싶은 사람", description: "ChatGPT를 넘어 실제 서비스를 만들고 싶은 사람" },
      { title: "포트폴리오가 필요한 사람", description: "취업이나 창업을 위해 실제 결과물이 필요한 사람" },
      { title: "새로운 것을 직접 만들고 싶은 사람", description: "개발 경험 없이도 AI와 하나씩 완성하고 싶은 사람" },
    ],
  },
  technology: {
    eyebrow: "YOUR AI BUILD TEAM",
    title: "도구는 어려운 이름보다\n역할만 이해하면 됩니다.",
    items: [
      { name: "ChatGPT", role: "아이디어와 기획", description: "무엇을 만들지 함께 정리합니다." },
      { name: "Codex", role: "실제 코드 제작", description: "말로 요청한 내용을 코드로 구현합니다." },
      { name: "GitHub", role: "프로젝트 저장소", description: "만든 홈페이지 코드를 안전하게 관리합니다." },
      { name: "Vercel", role: "인터넷 배포", description: "완성된 홈페이지를 실제 URL로 공개합니다." },
      { name: "Supabase", role: "필요할 때 데이터 저장", description: "회원가입, 로그인, 게시판 기능을 확장할 때 사용합니다." },
    ],
  },
  comparison: {
    eyebrow: "BEFORE / AFTER",
    title: "예전에는 이렇게 만들었습니다",
    before: { label: "기존 방식", flow: "기획 → 디자인 → 코딩 → 개발 → 서버 → 배포", description: "시간이 오래 걸리고 전문적인 지식이 필요했습니다." },
    after: { label: "AI 시대", flow: "아이디어 → AI 제작 → 수정 → 배포", description: "아이디어와 AI 활용 능력이 중요해졌습니다." },
  },
  projects: {
    eyebrow: "PROJECT IDEAS",
    title: "무엇을 만들 수 있나요?",
    description: "주제와 목적을 말하면 필요한 정보 구조와 화면부터 함께 만듭니다.",
    items: [
      { type: "BUSINESS", title: "사업 홈페이지", description: "회사 · 개인사업자 · 브랜드", accent: "상담 요청" },
      { type: "COMMERCE", title: "쇼핑몰", description: "상품 소개 · 판매 · 주문", accent: "상품 보기" },
      { type: "PORTFOLIO", title: "포트폴리오", description: "개발자 · 디자이너 · 프리랜서", accent: "프로젝트" },
      { type: "COMMUNITY", title: "커뮤니티", description: "모임 · 스터디 · 동호회", accent: "참여하기" },
      { type: "BOOKING", title: "예약 서비스", description: "골프 · 레스토랑 · 클래스 · 상담", accent: "예약하기" },
      { type: "AI SERVICE", title: "AI 서비스", description: "추천 · 검색 · 자동화 · 콘텐츠 생성", accent: "AI 시작" },
    ],
  },
  classPreview: {
    eyebrow: "4-WEEK PRACTICAL CLASS",
    title: "4주 동안 하나의\n실제 홈페이지를 완성합니다.",
    weeks: [
      { week: "1주차", title: "아이디어 → 기획 → 화면 구성" },
      { week: "2주차", title: "AI를 활용한 홈페이지 제작" },
      { week: "3주차", title: "기능 추가 → 수정 → 모바일 최적화" },
      { week: "4주차", title: "GitHub → Vercel → 실제 URL 배포" },
    ],
    promise: "4주 후에는 ‘배웠습니다’가 아니라 ‘제가 만든 홈페이지가 있습니다’라고 말할 수 있게 합니다.",
    action: { label: "4주 실전 클래스 신청하기", href: "/education/join.html" },
  },
  pricing: {
    eyebrow: "STARTER CLASS",
    title: "처음 시작하는 사람을 위한 실전 클래스",
    included: ["AI 홈페이지 제작", "Codex 활용법", "GitHub 사용법", "Vercel 배포", "실제 프로젝트 제작", "모바일 최적화", "프로젝트 완성까지 실습"],
    action: { label: "클래스 신청하기", href: "/education/join.html" },
  },
  setup: {
    eyebrow: "BEFORE YOU START",
    title: "처음 한 번만,\n작업 환경을 연결합니다.",
    description: "ChatGPT·Codex, Git·GitHub, Vercel까지 연결하면 채팅으로 수정한 홈페이지가 자동 배포됩니다. Supabase는 로그인이나 데이터 저장이 필요할 때만 추가합니다.",
    requiredLabel: "필수 준비",
    optionalLabel: "선택 기능",
    rolesTitle: "각 서비스는 이런 역할을 합니다.",
    rolesDescription: "코드를 만드는 도구, 저장하는 공간, 실행하는 서버와 데이터를 보관하는 데이터베이스를 나눠 연결합니다.",
    roles: [
      { name: "Codex", role: "제작·수정", description: "채팅 요청을 이해해 React·Next.js 코드와 홈페이지 내용을 수정하고 검사합니다.", status: "작업 도구" },
      { name: "Git", role: "변경 이력", description: "수정된 파일의 버전을 기록하고 이전 정상 상태로 되돌릴 수 있게 합니다.", status: "필수" },
      { name: "GitHub", role: "코드 저장", description: "React·Next.js 소스코드와 Git 변경 이력을 온라인 저장소에 보관합니다.", status: "필수" },
      { name: "Vercel", role: "프론트·백엔드 배포", description: "화면과 Next.js API를 운영 서버에 배포하고 도메인·SSL·자동 배포를 담당합니다.", status: "필수" },
      { name: "Supabase", role: "로그인·DB·CRUD", description: "회원 인증과 데이터 생성·조회·수정·삭제, 파일 저장 기능을 제공합니다.", status: "필요할 때" },
    ],
    flow: ["Codex 수정", "Git 기록", "GitHub 저장", "Vercel 배포", "Supabase 데이터"],
    steps: [
      { number: "01", title: "ChatGPT 가입 · Codex 준비", description: "ChatGPT 계정으로 데스크톱 앱에 로그인하고 홈페이지 폴더를 Codex에서 엽니다.", checklist: ["ChatGPT 계정 생성과 로그인", "ChatGPT 데스크톱 앱 설치", "프로젝트 폴더 열기", "Codex를 선택해 첫 요청 보내기"], action: { label: "공식 시작 안내", href: "https://learn.chatgpt.com/docs/quickstart" } },
      { number: "02", title: "Git 설치 · 사용자 설정", description: "Windows에 Git을 설치하고 터미널을 다시 연 뒤 이름과 이메일을 등록합니다.", checklist: ["Git for Windows 설치", "git --version으로 설치 확인", "커밋 작성자 이름·이메일 설정"], commands: ["winget install --id Git.Git -e --source winget", "git --version", "git config --global user.name \"YOUR_NAME\"", "git config --global user.email \"YOUR_EMAIL\""], action: { label: "Git 설치 안내", href: "https://git-scm.com/install/windows" } },
      { number: "03", title: "GitHub 가입 · 저장소 생성", description: "GitHub에 빈 저장소를 만들고 로컬 홈페이지의 main 브랜치를 연결해 Push합니다.", checklist: ["GitHub 계정 생성", "New repository 선택", "기존 파일이 있다면 README 없이 빈 저장소 생성", "origin 연결 후 main Push"], commands: ["git init -b main", "git add .", "git commit -m \"first commit\"", "git remote add origin https://github.com/USERNAME/REPOSITORY.git", "git push -u origin main"], action: { label: "저장소 연결 안내", href: "https://docs.github.com/en/migrations/importing-source-code/using-the-command-line-to-import-source-code/adding-locally-hosted-code-to-github" } },
      { number: "04", title: "Vercel 가입 · 자동 배포", description: "GitHub 계정으로 Vercel에 가입하고 저장소를 Import하면 main Push마다 운영 주소가 갱신됩니다.", checklist: ["GitHub로 Vercel 가입", "Add New → Project", "GitHub 저장소 Import", "Framework Preset: Next.js 확인", "Deploy 후 READY와 운영 URL 확인"], action: { label: "Git 배포 안내", href: "https://vercel.com/docs/git" } },
    ],
    optional: {
      number: "05", title: "Supabase — 로그인·DB가 필요할 때만", description: "현재 소개 홈페이지와 Codex 배포 흐름에는 필요하지 않습니다. 회원 로그인, 문의 저장, 관리자 데이터가 생길 때 연결합니다.",
      checklist: ["Supabase 프로젝트 생성", "Connect 화면에서 URL·Publishable key 확인", ".env.local과 Vercel 환경변수에 같은 값 등록", "데이터 테이블의 RLS 정책 점검"],
      env: ["NEXT_PUBLIC_SUPABASE_URL=...", "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=..."], warning: "Secret·service role 키는 NEXT_PUBLIC에 넣거나 GitHub에 올리면 안 됩니다.",
      action: { label: "Next.js 연결 안내", href: "https://supabase.com/docs/guides/getting-started/quickstarts/nextjs" },
    },
  },
  showcase: {
    eyebrow: "ONE WORKFLOW, MANY RESULTS",
    title: "주제가 달라지면,\n결과도 달라집니다.",
    description: "같은 템플릿에 문구만 바꾸는 방식이 아닙니다. 업종과 고객, 원하는 분위기에 맞춰 정보 구조부터 색상과 화면 표현까지 함께 조정합니다.",
    imageAlt: "카페, 전문 컨설팅, 크리에이티브 포트폴리오 홈페이지가 데스크톱과 모바일 화면에 적용된 예시",
    cases: [
      { type: "CAFE", title: "따뜻한 로컬 카페", request: "베이지와 짙은 갈색으로 편안한 매장 분위기를 보여줘.", result: "메뉴 · 공간 소개 · 방문 CTA" },
      { type: "STUDIO", title: "신뢰감 있는 전문 스튜디오", request: "서비스 강점이 명확하고 상담으로 자연스럽게 이어지게 해줘.", result: "서비스 · 업무 방식 · 상담 CTA" },
      { type: "PORTFOLIO", title: "선명한 크리에이티브 포트폴리오", request: "작업물이 먼저 보이고 개성이 강한 화면으로 바꿔줘.", result: "프로젝트 · 소개 · 협업 CTA" },
    ],
  },
  examples: {
    eyebrow: "PROMPT EXAMPLES",
    title: "이렇게 요청하면 됩니다.",
    items: [
      "카페 홈페이지로 바꾸고 베이지와 짙은 갈색을 사용해줘.",
      "서비스 소개 아래에 가격표와 상담 신청 버튼을 추가해줘.",
      "대표 이미지를 교체하고 모바일 화면의 글자 크기를 조정해줘.",
      "오류를 검사한 다음 GitHub와 Vercel에 배포해줘.",
    ],
  },
  deployment: {
    eyebrow: "SAFE DEPLOYMENT",
    title: "바로 올리지 않고,\n확인한 뒤 배포합니다.",
    points: [
      { title: "변경 범위 확인", description: "기존 작업과 디자인을 보존하면서 요청한 부분만 수정합니다." },
      { title: "품질 검사", description: "코드 오류와 빌드 실패 여부를 확인하고 통과한 변경만 저장합니다." },
      { title: "배포 이력", description: "GitHub 커밋과 Vercel 배포가 연결되어 언제든 변경 내역을 확인할 수 있습니다." },
      { title: "운영 확인", description: "배포 상태가 READY인지 확인하고 실제 주소에서 최신 화면이 열리는지 검사합니다." },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    title: "자주 묻는 질문",
    items: [
      { question: "코딩을 전혀 몰라도 가능한가요?", answer: "가능합니다. AI에게 원하는 결과를 자연어로 설명하고 결과를 확인하면서 수정하는 방식으로 진행합니다." },
      { question: "React를 꼭 알아야 하나요?", answer: "처음부터 React를 요구하지 않습니다. 프로젝트 수준에 맞춰 필요한 기술을 단계적으로 사용합니다." },
      { question: "홈페이지를 실제 인터넷에 올릴 수 있나요?", answer: "가능합니다. GitHub와 Vercel을 활용해 실제 URL로 배포하는 것까지 경험합니다." },
      { question: "완성된 홈페이지를 나중에 수정할 수 있나요?", answer: "가능합니다. AI에게 원하는 수정 내용을 설명하면서 계속 개선할 수 있습니다." },
      { question: "어떤 홈페이지를 만들 수 있나요?", answer: "회사 홈페이지, 개인 홈페이지, 포트폴리오, 모임, 쇼핑몰, 예약 서비스 등 다양한 형태로 확장할 수 있습니다." },
      { question: "AI가 모든 것을 알아서 해주나요?", answer: "아닙니다. AI에게 정확하게 요구하고 결과를 확인하고 수정하는 능력을 배우는 것이 클래스의 핵심입니다." },
    ],
  },
  finalCta: {
    eyebrow: "START YOUR FIRST SITE",
    title: "아이디어만 가지고 오세요.\nAI와 함께 첫 번째 홈페이지를 완성해보세요.",
    description: "코딩을 잘하는 사람이 아니라 AI를 잘 활용하는 사람이 만드는 시대입니다.",
    action: { label: "지금 시작하기", href: "/education/join.html" },
  },
  footer: {
    description: "Codex 채팅 기반 홈페이지 제작·수정·배포 워크플로",
    repository: "https://github.com/cursaman/autosites",
  },
} as const;

export const courseContent = {
  hero: {
    eyebrow: "BEGINNER-FRIENDLY · 4-WEEK PRACTICAL COURSE",
    title: "4주 뒤, 직접 만든\n홈페이지 주소를 가져가세요.",
    description: "코드를 외우는 수업이 아닙니다. 만들고 싶은 홈페이지를 Codex에 설명하고, 직접 수정하고, GitHub에 저장한 뒤 Vercel 운영 주소로 공개하는 과정을 함께 완성합니다.",
    facts: ["4주", "매주 토요일", "오후 6시–8시", "총 8시간", "최대 8명"],
  },
  promise: {
    eyebrow: "WHY THIS COURSE",
    title: "혼자서는 막히는 지점을\n수업에서 함께 넘습니다.",
    concerns: [
      { question: "무엇부터 시작해야 할지 모르겠어요.", answer: "설치부터 첫 요청까지 같은 화면을 보며 함께 시작합니다." },
      { question: "AI가 만든 코드를 믿어도 될까요?", answer: "결과를 확인하고 오류를 검사하고 다시 요청하는 방법을 배웁니다." },
      { question: "만들어도 인터넷에 올리지 못할 것 같아요.", answer: "GitHub 저장부터 Vercel 운영 주소 확인까지 직접 실습합니다." },
    ],
    deliverablesTitle: "4주 뒤 내 손에 남는 것",
    deliverables: [
      { number: "01", title: "내 주제의 반응형 홈페이지", description: "가게, 서비스, 포트폴리오 등 자신에게 필요한 내용으로 제작합니다." },
      { number: "02", title: "GitHub 코드 저장소", description: "모든 작업 이력을 내 계정에 안전하게 보관합니다." },
      { number: "03", title: "실제로 열리는 운영 URL", description: "휴대폰이나 다른 사람의 컴퓨터에서도 접속할 수 있게 배포합니다." },
      { number: "04", title: "다시 수정하고 배포하는 방법", description: "수업 이후에도 Codex와 대화하며 스스로 운영할 수 있습니다." },
    ],
  },
  progress: {
    eyebrow: "COHORT 01",
    title: "1기 교육이 진행 중입니다.",
    description: "첫 수업에서 웹의 작동 원리와 Codex, Git, GitHub, Vercel의 역할을 배우고 작업환경을 준비했습니다.",
    sessions: [
      { week: "1주차", date: "8월 29일", topic: "웹과 작업환경 이해", status: "완료" },
      { week: "2주차", date: "9월 5일", topic: "랜딩페이지 제작", status: "예정" },
      { week: "3주차", date: "9월 12일", topic: "GitHub·Vercel 배포", status: "예정" },
      { week: "4주차", date: "9월 19일", topic: "수정과 운영", status: "예정" },
    ],
  },
  records: {
    eyebrow: "CLASS RECORDS",
    title: "수업이 끝날 때마다 기록합니다.",
    description: "완료된 수업에서 실제로 다룬 내용과 다음 단계에 필요한 결과물을 공개합니다. 수강생 개인정보는 포함하지 않습니다.",
    items: [
      { week: "1주차", date: "2026. 08. 29", title: "웹과 작업환경 준비 완료", summary: "웹사이트의 기본 구조를 이해하고 Codex, Git, GitHub, Vercel이 각각 어떤 역할을 하는지 확인했습니다.", completed: ["ChatGPT·Codex 작업 방식 이해", "Git 설치와 작성자 설정", "GitHub 저장소 생성", "첫 커밋과 Push 실습"], next: "2주차에는 자신의 홈페이지 주제와 고객을 정하고 반응형 랜딩페이지를 제작합니다." },
    ],
  },
  audience: ["코딩을 처음 접하는 분", "직접 홈페이지를 만들고 싶은 분", "소상공인과 1인 사업자", "제작 이후 수정과 배포까지 배우고 싶은 분"],
  curriculum: [
    { week: "01", title: "웹과 작업환경 이해", objective: "홈페이지 제작에 필요한 도구의 역할을 이해하고 개인 작업환경을 준비합니다.", status: "완료", items: ["웹사이트가 작동하는 방법", "Codex·Git·GitHub·Vercel 역할", "Git 설치와 저장소 생성"], schedule: [{ time: "18:00", lesson: "웹사이트와 바이브코딩 이해" }, { time: "18:25", lesson: "Codex·GitHub·Vercel 역할" }, { time: "18:50", lesson: "ChatGPT·Git 설치와 설정" }, { time: "19:25", lesson: "GitHub 저장소 생성·첫 Push" }], result: "작업환경과 GitHub 저장소" },
    { week: "02", title: "랜딩페이지 제작", objective: "만들고 싶은 홈페이지를 설명하고 반응형 랜딩페이지를 완성합니다.", status: "예정", items: ["홈페이지 주제와 고객 정하기", "Codex 요청문 작성", "문구·색상·모바일 화면 수정"], schedule: [{ time: "18:00", lesson: "업종·고객·목표 정하기" }, { time: "18:25", lesson: "홈페이지 요청문 작성" }, { time: "18:50", lesson: "Codex로 화면 제작" }, { time: "19:30", lesson: "모바일·문구·색상 수정" }], result: "반응형 랜딩페이지" },
    { week: "03", title: "실제 홈페이지 배포", objective: "제작한 코드를 안전하게 저장하고 누구나 접속할 수 있는 주소로 공개합니다.", status: "예정", items: ["Git 변경사항 저장", "GitHub main Push", "Vercel 연결과 운영 URL 확인"], schedule: [{ time: "18:00", lesson: "저장과 배포의 차이" }, { time: "18:20", lesson: "Git 상태 확인·커밋" }, { time: "18:50", lesson: "GitHub main Push" }, { time: "19:20", lesson: "Vercel 연결·운영 검사" }], result: "공개된 홈페이지 주소" },
    { week: "04", title: "수정과 운영", objective: "운영 홈페이지를 다시 수정하고 검사와 재배포를 스스로 반복합니다.", status: "예정", items: ["Codex로 내용 다시 수정", "오류 검사와 자동 재배포", "도메인·Supabase·CRUD 이해"], schedule: [{ time: "18:00", lesson: "실제 수정 요청 작성" }, { time: "18:30", lesson: "빌드 검사·오류 해결" }, { time: "19:00", lesson: "자동 재배포와 운영 확인" }, { time: "19:30", lesson: "도메인·로그인·CRUD 이해" }], result: "스스로 운영하는 작업 흐름" },
  ],
  outcomes: ["Codex로 홈페이지 제작·수정", "Git으로 변경 이력 관리", "GitHub에 소스코드 보관", "Vercel로 화면과 API 배포", "로그인·데이터베이스가 필요한 시점 구분"],
  completion: {
    eyebrow: "RESULTS & NEXT COHORT",
    title: "1기의 과정이\n다음 기수의 안내가 됩니다.",
    description: "1기는 현재 진행 중입니다. 수업이 끝날 때마다 실제 결과를 기록하고, 과정 종료 후 공개 동의를 받은 결과물과 후기만 소개합니다.",
    status: "1기 진행 중",
    resultSlots: [
      { title: "수강생 홈페이지", timing: "2~4주차 이후", description: "완성된 홈페이지 중 공개에 동의한 결과물과 운영 주소를 소개합니다." },
      { title: "수강 후기", timing: "4주차 이후", description: "실명 대신 닉네임 사용이 가능하며 공개에 동의한 후기만 게시합니다." },
      { title: "교육 현장 기록", timing: "수업 종료 후", description: "참여자의 얼굴이나 개인정보가 노출되지 않도록 확인한 사진만 사용합니다." },
    ],
    privacy: "결과물·후기·사진 공개 여부는 교육 참여와 별개이며, 동의하지 않아도 불이익이 없습니다.",
  },
  nextCohort: {
    label: "2기 사전 관심 접수",
    title: "다음 4주 과정은 1기 종료 후 안내합니다.",
    description: "희망 요일과 만들고 싶은 홈페이지를 당근 채팅으로 남겨주시면 2기 일정이 확정될 때 모임에서 확인할 수 있습니다.",
    schedule: "일정 준비 중",
    actionLabel: "당근 모임에서 2기 문의하기",
  },
  fee: { amount: "50,000원", label: "4주 전체 교육비", description: "별도의 장소 이용료 없이 4주 수업과 실습 환경이 모두 포함됩니다.", included: ["주 1회 2시간 · 총 8시간 실습", "커피긱스 2층 8인룸", "수업용 빔프로젝터", "매회 커피 제공"] },
  venue: {
    name: "커피긱스 2층 8인룸", address: "부산광역시 연제구 교대로24번길 7", description: "부산교육대학교 인근 · 주차 가능", time: "매주 토요일 오후 6시–8시",
    details: ["오후 6시 정시 시작", "2층 8인룸으로 이동", "건물 주차 가능", "Wi-Fi는 현장에서 안내"],
    mapUrl: "https://map.kakao.com/link/search/부산광역시%20연제구%20교대로24번길%207",
  },
  preparation: ["개인 노트북", "노트북 충전기", "사용 가능한 이메일 계정"],
  recruitment: {
    title: "최대 8명의 소규모 실습",
    description: "현재 당근의 부산 사직동 바이브코딩 모임에서 수강 문의를 받고 있습니다. 모임 페이지에서 참여 가능 여부를 문의해 주세요.",
    status: "당근에서 모집 중",
    capacity: "정원 8명 · 자리 확인 후 신청 확정",
    steps: [
      { number: "01", title: "당근 모임 열기", description: "부산 사직동 바이브코딩 모임 페이지로 이동합니다." },
      { number: "02", title: "채팅으로 문의", description: "참여 가능한 날짜와 만들고 싶은 홈페이지를 알려주세요." },
      { number: "03", title: "자리 확인", description: "남은 자리와 수업 준비사항을 채팅으로 안내받습니다." },
      { number: "04", title: "신청 확정", description: "확정 안내를 받으면 오후 6시 수업에 참여합니다." },
    ],
    inquiryItems: ["이름 또는 당근 닉네임", "참여 가능한 수업 날짜", "개인 노트북 보유 여부", "만들고 싶은 홈페이지 주제"],
    privacy: "이 페이지에서는 이름·전화번호·이메일을 수집하거나 공개하지 않습니다. 교육 운영에 필요한 연락은 당근 채팅으로 진행합니다.",
    action: { label: "당근 모임에서 문의하기", href: "https://www.daangn.com/kr/group/%EB%B6%80%EC%82%B0-%EC%82%AC%EC%A7%81%EB%8F%99-%EB%B0%94%EC%9D%B4%EB%B8%8C%EC%BD%94%EB%94%A9-%EB%AA%A8%EC%9E%84-vxbz4quk5ntg/" },
  },
} as const;
